In [1]:
import sympy as sym
import numpy as np
from IPython.display import display,Math

In [2]:
A = [[1,2],[3,4]]
type(A)

list

#In order to convert a list into a matrix do the following:

In [4]:
A = np.array([[1,2],[3,4]])
type(A)

numpy.ndarray

In [6]:
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [7]:
mat = np.zeros([4,6])
mat[2,4] = 8
mat[1,3] = 7
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
numrange = range(0,4)
for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (1+rowi)
mat        

array([[1., 1., 1., 1., 0., 0.],
       [2., 2., 2., 2., 0., 0.],
       [3., 3., 3., 3., 8., 0.],
       [4., 4., 4., 4., 0., 0.]])

In [14]:
x,y = sym.symbols('x y')
Fxy = (4+x)*(2-y)
xyset = range(0,3)
outmat = np.zeros([len(xyset),len(xyset)])
for i in xyset:
    for j in xyset:
        outmat[i,j] = Fxy.subs({x:i,y:j})
display(Math(sym.latex(sym.sympify(outmat))))
outmat        

<IPython.core.display.Math object>

array([[ 8.,  4.,  0.],
       [10.,  5.,  0.],
       [12.,  6.,  0.]])

### Multiplication table

In [19]:
nums = range(0,11)
matmult = np.zeros((len(nums),len(nums)),dtype=int)
for rowi in nums:
    for coli in nums:
        matmult[rowi,coli] = rowi*coli
display(Math(sym.latex(sym.sympify(matmult))))

<IPython.core.display.Math object>